version: "3"
services:
  goods-service:
    image: goods-service
    container_name: goods-service
    environment:
      PROFILE: dev
      JAVA_OPTS: "-server -Xms768m -Xmx768m"
    volumes:
      - /opt/jar:/opt/jar
    restart: always
    ports:
      - "5053:5053"
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    environment:
      PROFILE: dev
      JAVA_OPTS: "-server -Xms768m -Xmx768m"
    volumes:
      - /opt/jar:/opt/jar
    restart: always
    ports:
      - "5054:5054"
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /opt/www/service/nginx/log:/var/log/nginx
      - /opt/www/service/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/www/service/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"