spring:
  datasource:
    ##spring.datasource.maxIdle=30
    minIdle: 5
    maxActive: 100
    initialSize: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    filters: stat # ,wall,log4j
    connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    druidLoginName: dmcp
    druidPassword: dmcp
    type: com.alibaba.druid.pool.DruidDataSource

## order-service
order-service:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
## goods-service
goods-service:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
## seckill-service
seckill-service:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456